[package]
name = "tokio-udev"
version = "0.2.0"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]
license = "Apache-2.0/MIT"
description = "Tokio support for udev device events."
repository = "https://github.com/jeandudey/tokio-udev"
homepage = "https://github.com/jeandudey/tokio-udev"
documentation = "https://docs.rs/tokio-udev"
edition = "2018"

[dependencies]
libc = "0.2"

mio = "0.6"
mio-udev = { path = "../mio-udev", version = "0.2.0" }

tokio = { version = "^0.2.5", features = ["io-driver", "stream"] }

[dev-dependencies]
tokio = { version = "0.2", features = ["macros"] }
